return [[
# mesh compile version: 2.00
thank u for even usin' ts :33333

Just put all your objs into "obj" folder

And then you just execute "objtomesh.exe," and the output should be a "[FileName].mesh" inside the "mesh" folder.

If you want to use that mesh in the studio

Then proceed to "%localappdata%/Roblox/Versions/your-studio-version/content"

and choose any folder or make one yourself and then put the mesh file into it.

Afterwards, proceed to Roblox Studio and paste this into MeshID (meshpart or specialMesh): "rbxasset://path/to/your/mesh.mesh"

ya done!
]]
