return [[
# version 0.0.1, mesh compile version: 1.00
thank u for even usin' ts :33333

Ahem... since it was built on Zune, I, uh. I don't know if I was able to get all the files inside a folder whatsoever. (Zune 0.5.8)

So unfortunately it uses the crutches method (just like I like it.)

You'll have to put your .obj file into the "obj" folder and rename it to "file.obj."

And then you just execute "objtomesh.exe," and the output should be a "file.mesh" inside the "mesh" folder.

If you want to use that mesh in the studio

Then proceed to "%localappdata%/Roblox/Versions/your-studio-version/content."

and choose any folder or make one yourself and then put the "file.mesh" into it.

Afterwards, proceed to Roblox Studio and paste this into MeshID (meshpart or specialMesh): "rbxasset://path/to/your/mesh.mesh."

ya done!
]]
